name: Continuous Integration (CI)

## Run CI jobs on all branches by default
on:
  push:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Run unit tests
        run: ./gradlew test
      - name: Run unit tests and generate JaCoCo test report
        run: ./gradlew test
      - name: Generate JaCoCo badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
            jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
            generate-branches-badge: true
      - name: Commit and push the badge (if it changed)
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          if [[ `git status --porcelain *.svg` ]]; then
            git config user.name “Wahyu Hidayat“
            git config user.email 'wahyuhidayaat510@gmail.com'
            git add *.svg
            git commit -m "chore: autogenerated JaCoCo coverage badges"
            git -c http.extraHeader="AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.MY_PERSONAL_TOKEN }} | base64)" push
          fi